config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#home'

  post 'courses/search_courses', to: 'courses#update_index'
  get 'about',       to: 'pages#about'
  resources :courses do
    resources :reviews, only: [:new, :create]
    resources :payments, only: [:new, :create]
  end

  resources :favorites, only: [:index, :create, :destroy ]

  resources :bookings, only: [:index, :show, :create, :destroy] do
    # resources :payments, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :studios

  # Attachinary route
  mount Attachinary::Engine => "/attachinary"
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :course

  validates :course, uniqueness: { scope: :user, message: "is already booked by user" }
  validates_with BookingCountValidator

  monetize :amount_cents
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    # @booking = Booking.where(state: 'paid').find(params[:id])
  end

  def create
    # @booking = Booking.new(bookings_params)
    # if @booking.save
    #   respond_to do |format|
    #     format.html { redirect_to user_path(current_user) }
    #     format.js
    #   end
    # else
    #   @course = Course.find(bookings_params[:course_id])
    #   respond_to do |format|
    #     format.html { render 'courses/show' }
    #     format.js
    #   end
    # end

    # @course = Course.find(params[:course_id])
    # @studio = @course.studio
    # @booking = Booking.new(amount: @course.price, state: 'pending', course: @course, user: current_user)
    # if @booking.save
    #   redirect_to new_booking_payment_path(@booking)
    # else
    #   render 'courses/show'
    # end

    @course = Course.find(params[:booking][:course_id])
    @studio = @course.studio
    @booking = Booking.new(amount: @course.price, state: 'pending', course: @course, user: current_user)
    if @booking.valid?
      respond_to do |format|
        format.html { redirect_to new_course_payment_path(@course) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'courses/show' }
        format.js
      end
    end

  end

  def destroy
    @booking = Booking.find(params[:id]).destroy
    redirect_to user_path(current_user)
  end


end

app/views/bookings/_booking_confirm_message.html.erb
<div class="text-center confirm-messages">
  <i class="fa fa-check-circle fa-2x booking-checked"></i>
  <p>Booking confirmed!</p>
  <%= link_to user_path(current_user) do %>
    Go to my bookings
  <% end %>
</div>

app/views/bookings/_booking_error_message.html.erb
<ul class="list-unstyled review-error-message">
  <li class="text-center"><i class="fa fa-exclamation-circle"></i> Course <%= @booking.errors[:course][0] %></li>
</ul>

app/views/bookings/_index.html.erb
<!-- This file is a partial (hence the underscore in the title) rendered in Users#show view -->

<div class="col-xs-12 booking-wrap no-padding">

          <% if b.course.studio.photo %>
            <div class="booking-picture" style="background-image: url('<%= cl_image_path b.course.studio.photo.path %>');"></div>

          <% else %>
            <div class="booking-picture" style="background-image: url('<%= cl_image_path b.course.studio.cld_id %>');"></div>
          <% end %>



  <div class="booking-list-content">
  <div class="booking-top">
    <div class="booking-title">
      <p class="booking-time-span"><%= b.course.start_time.day %> <%= b.course.start_time.strftime("%B") %> <%= b.course.start_time.hour %> - <%= b.course.end_time.hour %> h</p>
    </div>
    <div class ="booking-cost">
      <p><%= humanized_money_with_symbol(b.course.price) %></p>
    </div>
  </div>

    <div class="booking-list-info">
      <p>
        <strong><%= b.course.title %></strong>  with <%= b.course.instructor.first_name  %>
        <br>
        <span class="course-where"><%= b.course.studio.name %> <%= b.id %> </span>
      </p>
    </div>
    <% if old %>
      <%= link_to new_course_review_path(course_id: b.course), class: "review-me" do %>
        <i class="fa fa-star"></i> Review
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/_login.html.erb
<% if current_user %>
  <button class="new-booking-button text-center" data-toggle="modal" data-target="#bookingLoginModal">
    <h3 class="new-booking-heading">Join</h3>
  </button>
<% else %>
  <%= link_to new_user_session_path do %>
    <button class="new-booking-button text-center">
      <h3 class="new-booking-heading">Login To Book</h3>
    </button>
  <% end %>
<% end %>

app/views/bookings/_new.html.erb
<!-- This file is a partial (hence the underscore in the title) rendered in Courses#show view -->

<!-- Booking Modal -->
<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog center-modal-box" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>

        <h4 class="modal-title booking-modal-title" id="myModalLabel">
          Confirmation
        </h4>
      </div>
      <div class="modal-body booking-modal-body">
        <%= @course.title %>
        <br>
        <div class="confirmation-date">
          <%= date_words(@course.start_time) %> - <%= @course.start_time.strftime ("%l:%M %P") %>
        </div>
        <div class="confirmation-address">
          <%= @course.studio.address %>
        </div>
        <div class="booking-modal-cost">
          <%= humanized_money_with_symbol(@course.price) %>
        </div>

        <div class="payment">
          <%= form_tag bookings_path do %>
            <%= hidden_field_tag 'course_id', @course.id %>
            <%= submit_tag 'Purchase', class: 'btn btn-primary' %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/bookings/create.js.erb
$('#payment-modal').html("<%= j render 'payments/new', booking: @booking %>");
$("#bookingModal").modal();

app/views/bookings/show.html.erb
<div class="booking-show-container">
  <h1>Bookings</h1>
  <ul>
    <li>Status: <%= @booking.state %></li>
    <li>Course: <%= Course.find(@booking.course_id).title %> </li>
    <li>Amount: <%= humanized_money_with_symbol(@booking.amount) %></li>
  </ul>
</div>