config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#home'

  post 'courses/search_courses', to: 'courses#update_index'
  get 'about',       to: 'pages#about'
  resources :courses do
    resources :reviews, only: [:new, :create]
    resources :payments, only: [:new, :create]
  end

  resources :favorites, only: [:index, :create, :destroy ]

  resources :bookings, only: [:index, :show, :create, :destroy] do
    # resources :payments, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :studios

  # Attachinary route
  mount Attachinary::Engine => "/attachinary"
end

app/views/shared/_booking-list.html.erb
<div class="col-xs-12 booking-wrap">
  <div class="booking-top">
    <div class="booking-title">
      <p class="booking-time-span"><%= b.course.start_time.day %> <%= b.course.start_time.strftime("%B") %> <%= b.course.start_time.hour %> - <%= b.course.end_time.hour %> h</p>
    </div>

    <div class ="booking-cost">
      <% cost_amount = b.course.cost %>
      <% if cost_amount.to_i - cost_amount == 0 %>
      <p><%= cost_amount.to_i %> €</p>
      <% else %>
      <p><%= cost_amount.round(3) %> €</p>
      <% end %>
    </div>
  </div>

  <div class="booking-list-content">
    <p><strong><%= b.course.title %></strong> | <span class="course-where"><%= b.course.studio.name %></span></p>
    <% if old %>
      <%= link_to new_course_review_path(course_id: b.course), class: "review-me" do %>
        <i class="fa fa-pencil-square-o"></i>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_booking_modal.html.erb
<button class="new-booking-button" data-toggle="modal" data-target="#bookingModal">
  <h3 class="text-center">Join</h3>
</button>

<div class="modal fade" id="bookingModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog center-modal-box" role="document">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title booking-modal-title" id="myModalLabel">
          Confirmation
        </h4>
      </div>
      <div class="modal-body booking-modal-body">
        <%= course.title %>
        <br>
        <div class="confirmation-date">
          <%= date_words %> - <%= course.start_time.strftime ("%l:%M %P") %>
        </div>
        <div class="confirmation-address">
          <%= course.studio.address %>
        </div>
        <div class="booking-modal-cost">
          <% cost_amount = course.cost %>
          <% if cost_amount - cost_amount.to_i == 0 %>
            <%= cost_amount.to_i %> <i class="fa fa-euro"></i>
          <% else %>
            <%= course.cost%> <i class="fa fa-euro"></i>
          <% end %>
        </div>
        <%= simple_form_for(Booking.new, remote: true) do |f| %>
          <%= f.input :user_id, as: :hidden, input_html: { value: current_user.id } %>
          <%= f.input :course_id, as: :hidden, input_html: { value: course.id } %>
          <div class="text-center confirm-button-margin">
            <%= f.submit "Confirm", class: "btn btn-confirm" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_course_card.html.erb
<div class="row-course">
    <div class="col-xs-12 course-cards-container course-color">
      <div class="course-card">
        <div class="studio-picture" style="background-image: url('<%= cl_image_path course.studio.cld_id %>');">
          <!-- <img src="http://www.studio89fitness.com/images/background/6.jpg" alt="studio"> -->
        </div>
        <div class="info">
          <div class="spots">
            <%= course.spots - course.bookings.length %> spots left!
          </div>
          <div class="distance">
            <i class="fa fa-map-marker"></i> <%= course.studio.distance %> km
          </div>
          <p class="course-price"> <%= course.cost.round %>€ </p>
          <h3 class="course-title"> <%= course.title %> </h3>
          <div class="studio-title">
            <h4 class="studio-card-title"><%= course.studio.name %></h4>
          </div>
          <div class="star-ratings-css-small">
            <%= render 'shared/stars', course: course %>
          </div>
          <div class="course-times">
            <% if course.start_time.to_date == Date.today %>
              Today
            <% elsif course.start_time.to_date == (Date.today + 1) %>
              Tomorrow
            <% else %>
              <%= course.start_time.strftime('%A, %b %d') %>
            <% end %>
              <br><%= course.start_time.strftime("%l:%M %p") %> - <%= course.end_time.strftime("%l:%M %p") %>
          </div>
          <!-- <p class="level"><%= course.level %> </p> -->
        </div>
      </div>
    </div>
</div>

app/views/shared/_course_descriptions_icons.html.erb
<div class="course-description">
  <div class="duration course-icon-description">
    <div class="category-image">
      <%= cl_image_tag 'clock_abwox3' %>
    </div>
    <div class="category-description">
      <%= ((@course.end_time - @course.start_time)/60).round %> mins
    </div>
  </div>
  <div class="course-category course-icon-description">
    <div class="category-image">
      <% case @course.category %>
      <% when "Yoga" %>
        <%= cl_image_tag 'buddhist-yoga-pose_mgof1t' %>
        <% when "Pilates" %>
        <%= cl_image_tag 'buddhist-yoga-pose_mgof1t' %>
      <% when "Crossfit" %>
        <%= cl_image_tag 'weightlifting_xt40om' %>
      <% when "Kickboxing", "Martial Arts" %>
        <%=  cl_image_tag 'mma_ocfpf0' %>
      <% when "Dance" %>
        <%= cl_image_tag 'dancer_yncg7a' %>
      <% when "HIIT" %>
        <%= cl_image_tag 'stretch_ee1nkk' %>
      <% end %>
    </div>
    <div class="category-description">
      <%= @course.category %>
    </div>
  </div>
  <div class="course-intensity course-icon-description">
    <div class="category-image">
      <%= cl_image_tag 'settings_y1kkba' %>
    </div>
    <div class="category-description">
      <%= @course.level %>
    </div>
  </div>
</div>

<div class="class-description">
  <h4> About this course </h4>
  <p> <%= @course.description %></p>
</div>

app/views/shared/_flashes.html.erb
<!-- Leaving this in case we want to use this -->

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_sidenavbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand hidden-xs hidden-sm" do %>
    <%= image_tag "fitflex_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Favorites", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "All Courses", courses_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.facebook_picture_url %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% elsif current_user.photo? %>
            <%= cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag cl_image_path("twjchiqlm70j8zjkvk4l"), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to about_path do %>
                <i class="fa fa-home"></i>  <%= t(".about_us", default: "About Us") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
    <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Sidebar appearing on mobile only -->
  <% if user_signed_in? %>
    <!-- LOGO APP -->
    <%= link_to root_path, class: "navbar-wagon-brand hidden-md hidden-lg" do %>
      <%= image_tag "fitflex_logo.png" %>
    <% end %>

    <div class="sidenav" id="mySidenav">
      <i class="fa fa-times closebtn" onclick="closeNav()"></i>
      <div class="user-info">
        <% if current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar-xs dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% elsif current_user.photo? %>
          <%= cl_image_tag current_user.photo.path, class: "avatar-xs dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag cl_image_path('twjchiqlm70j8zjkvk4l'), class: "avatar-xs dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <h1> <%= current_user.first_name %> <%= current_user.last_name %></h1>
        <h2> <%= current_user.email %> </h2>
      </div>
      <div class="user-nav">
        <div class="user-nav-links">
          <%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Favorites", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "All Courses", courses_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
        </div>
        <div class="nav-social-media">
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-facebook"></i></a>
        </div>
      </div>
    </div>

    <div class="navbar-wagon-right hidden-md hidden-lg">
      <i class="fa fa-bars" style="cursor:pointer" onclick="openNav()"></i>
    </div>

  <% else %>
    <%= link_to root_path, class: "brand-not-logged-in hidden-md hidden-lg" do %>
      <%= image_tag "fitflex_logo.png" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_sidenavbar_solid.html.erb
<div class="navbar-wagon navbar-wagon-solid">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand hidden-xs hidden-sm" do %>
    <%= image_tag "fitflex_logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Favorites", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "All Courses", courses_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.facebook_picture_url %>
            <%= image_tag current_user.facebook_picture_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% elsif current_user.photo? %>
            <%= cl_image_tag current_user.photo.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= image_tag cl_image_path('twjchiqlm70j8zjkvk4l'), class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to user_path(current_user) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to about_path do %>
                <i class="fa fa-home"></i>  <%= t(".about_us", default: "About Us") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
    <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Sidebar appearing on mobile only -->
  <% if user_signed_in? %>
    <div class="go-back hidden-md hidden-lg">
    <%= link_to :back do  %>
      <i class="fa fa-chevron-left" aria-hidden="true"></i>
    <% end %>
    </div>
    <%= link_to root_path, class: "navbar-wagon-brand hidden-md hidden-lg" do %>
      <%= image_tag "fitflex_logo.png" %>
    <% end %>
    <div class="sidenav" id="mySidenav">
      <i class="fa fa-times closebtn" onclick="closeNav()"></i>
      <div class="user-info">
        <% if current_user.facebook_picture_url %>
          <%= image_tag current_user.facebook_picture_url, class: "avatar-xs dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% elsif current_user.photo? %>
          <%= cl_image_tag current_user.photo.path, class: "avatar-xs dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% else %>
          <%= image_tag cl_image_path('twjchiqlm70j8zjkvk4l'), class: "avatar-xs dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <% end %>
        <h1> <%= current_user.first_name %> <%= current_user.last_name %></h1>
        <h2> <%= current_user.email %> </h2>
      </div>
      <div class="user-nav">
        <div class="user-nav-links">
          <%= link_to "Profile", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "About Us", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Favorites", user_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "All Courses", courses_path(current_user), class: "navbar-wagon-item navbar-wagon-link" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-wagon-item navbar-wagon-link" %>
        </div>
        <div class="nav-social-media">
          <a href="#"><i class="fa fa-instagram"></i></a>
          <a href="#"><i class="fa fa-facebook"></i></a>
        </div>
      </div>
    </div>

    <div class="navbar-wagon-right hidden-md hidden-lg">
      <i class="fa fa-bars" style="cursor:pointer" onclick="openNav()"></i>
    </div>
  <% else %>
    <div class="go-back hidden-md hidden-lg">
      <%= link_to :back do  %>
        <i class="fa fa-chevron-left" aria-hidden="true"></i>
      <% end %>
    </div>
    <%= link_to root_path, class: "brand-not-logged-in hidden-md hidden-lg" do %>
      <%= image_tag "fitflex_logo.png" %>
    <% end %>
  <% end %>
</div>

app/views/shared/_stars.html.erb
<!-- Implementing font awesome stars -->
<% avg = course.average_rating %>
<% if avg >= 4.8 && avg <= 5 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
<% elsif avg >= 4.3 && avg < 4.8 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-half-o"></i>
<% elsif avg >= 3.8 && avg < 4.3 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg >= 3.3 && avg < 3.8 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-half-o"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg >= 2.8 && avg < 3.3 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg >= 2.3 && avg < 2.8 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-half-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg >= 1.8 && avg < 2.3 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg >= 1.3 && avg < 1.8 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-half-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg >= 0.8 && avg < 1.3 %>
  <i class="fa fa-star"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
<% elsif avg < 0.8 %>
  <i class="fa fa-star-half-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>
  <i class="fa fa-star-o"></i>

<% else %>
  <p> No Reviews </p>
<% end %>