config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'registrations' }
  root to: 'pages#home'

  post 'courses/search_courses', to: 'courses#update_index'
  get 'about',       to: 'pages#about'
  resources :courses do
    resources :reviews, only: [:new, :create]
    resources :payments, only: [:new, :create]
  end

  resources :favorites, only: [:index, :create, :destroy ]

  resources :bookings, only: [:index, :show, :create, :destroy] do
    # resources :payments, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :studios

  # Attachinary route
  mount Attachinary::Engine => "/attachinary"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :update_index]

  def index
    if params[:search_day]
      courses_by_day = filter_courses(params[:search_day])
      @courses = courses_by_day.reject { |course| course.bookings.length == course.spots }
    else
      @courses = Course.all
    end
    @filters = ["day", "category", "level", "distance", "price_cents"]
    @categories = Course.order(:category).distinct.pluck(:category)
  end

  def show
    @course = Course.find(params[:id])
    @booking = Booking.new
    if current_user
      @existing_booking = current_user.bookings.find_by_course_id(@course.id)
    end
    #@user = current_user

    # @la = location.latitude
    # @lo = location.longitude
    # Le Wagon Latitude and Longitude
    @la = 52.506913
    @lo = 13.391425
    @json_distance = distance_api_call(@la,@lo)
    @request = request.location
    @json_driving = duration_api_call(@la,@lo,"driving")
    @json_walking = duration_api_call(@la,@lo,"walking")
    @json_bicycle = duration_api_call(@la,@lo,"bicycling")
    @json_transit = duration_api_call(@la,@lo,"transit")
    @studio = @course.studio
    @hash = Gmaps4rails.build_markers(@studio) do |studio, marker|
      marker.lat studio.latitude
      marker.lng studio.longitude
      marker.infowindow render_to_string(partial: "/courses/map_box", locals: { studio: studio })
    end

    @date_words = date_words
    session[:current_course] = course_path(@course)

  end

  def new
    @course = Course.new
    @course
  end

  def create
    @course = Course.new(courses_params)
    @course.studio = current_user.studio
    if @course.save
      redirect_to course_path(@course)
    else
      render 'courses/new'
    end
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
    @course.update(courses_params)
    redirect_to courses_path
  end

  def destroy
    @destroy = Course.find(params[:id]).destroy
  end

  def update_index
    unless filter_params[:day] == ""
      day = filter_params[:day]
    else
      day = "Any day"
    end

    unless filter_params[:price_cents] == ""
      price_cents = filter_params[:price_cents]
    else
      price_cents = "Any price_cents"
    end
    category = filter_params[:category]
    level = filter_params[:level]
    input_price = filter_params[:price_cents]
    distance = filter_params[:distance].to_i

    @update_courses = filter_courses(day)

    case input_price
    when '€'
      @update_courses = @update_courses.where("price_cents >= ? AND price_cents < ?", 0, 700)
    when '€€'
      @update_courses = @update_courses.where("price_cents >= ? AND price_cents < ?", 700, 1500)
    when '€€€'
      @update_courses = @update_courses.where("price_cents >= ?", 1500)
    when ''
      @update_courses
    end

    # @update_courses = @update_courses.joins(:studio).where("studios.distance < #{distance}")
    @update_courses = @update_courses.where(level: level) unless level == ""
    @update_courses = @update_courses.where(category: category) unless category == ""

    respond_to do |format|
      format.html { redirect_to courses_path }
      format.js
    end
  end

  private

# Google Map
  require 'open-uri'

  def distance_api_call(la, lo)
   url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{la},#{lo}&destinations=#{URI.encode(@course.studio.address)}"
   form = open(url).read
   json =  JSON.parse(form)
   json["rows"][0]["elements"][0]["distance"]["text"]
  end

  def json_parsing_duration(url)
    form = open(url).read
    json = JSON.parse(form)
    json["rows"][0]["elements"][0]["duration"]["text"]
  end

  def duration_api_call(la,lo,mode)
    url = "https://maps.googleapis.com/maps/api/distancematrix/json?origins=#{la},#{lo}&destinations=#{URI.encode(@course.studio.address)}&mode=#{mode}&key=#{ENV['GOOGLE_API_SERVER_KEY']}"
    json_parsing_duration(url)
  end

  def location
    if request.location.ip == "127.0.0.1"
      Geocoder.search('85.214.132.117').first
    else
      request.location
    end
  end


# Filter Courses
  def filter_courses(day)

    case day
    when 'Today'
      Course.where("start_time > '#{Time.now}' AND start_time < '#{Time.now.end_of_day}'")
    when 'Tomorrow'
      Course.where("start_time > '#{Time.now.end_of_day}' AND start_time < '#{DateTime.tomorrow.end_of_day}'")
    when 'Any day'
      Course.where("start_time > '#{Time.now}' AND start_time < '#{(DateTime.now + 7.days).end_of_day}'")
    end
  end

  def courses_params
    params.require(:course).permit(:title, :date, :start_time, :end_time, :price_cents, :spots, :description, :category, :level, :studio_id)
  end

  def filter_params
    params.require(:search_courses).permit(:day, :category, :level, :distance, :price_cents)
  end

  def date_words
    datetime = @course.start_time
    if datetime.today?
      "Today"
    elsif datetime.to_date == Date.tomorrow
      "Tomorrow"
    elsif datetime < (DateTime.now + 7.day)
      days = datetime.day - DateTime.now.day
      if days == -1
        "Yesterday"
      elsif days < 0
        "#{-days} days ago"
      else
        "#{days} days"
      end
    end
  end
end

app/views/courses/_course_card.html.erb
  <div class="row-course">
      <div class="col-xs-12 course-cards-container course-color">
        <div class="course-card">
          <% if course.studio.photo %>
            <div class="studio-picture" style="background-image: url('<%= cl_image_path course.studio.photo.path %>');">
          <% else %>
            <div class="studio-picture" style="background-image: url('<%= cl_image_path course.studio.cld_id %>');">
          <% end %>
            <div id="course-12<%= course.id %>">
            <%= render "courses/course_favorite_button", course: course %>
            </div>
          </div>
          <div class="info">
            <div class="spots">
              <%= course.spots - course.bookings.length %> spots left!
            </div>
            <div class="distance">
              <i class="fa fa-map-marker"></i> <%= course.studio.distance %> km
            </div>
            <p class="course-price"> <strong> <%= humanized_money_with_symbol(course.price) %></strong></p>
            <h3 class="course-title"> <%= course.title %> </h3>
            <div class="studio-title">
              <h4 class="studio-card-title"><%= course.studio.name %></h4>
            </div>
            <div class="star-ratings-css-small">
              <%= render 'shared/stars', course: course %>
            </div>
            <div class="course-times">
              <% if course.start_time.to_date == Date.today %>
                Today
              <% elsif course.start_time.to_date == (Date.today + 1) %>
                Tomorrow
              <% else %>
                <%= course.start_time.strftime('%A, %b %d') %>
              <% end %>
              <br>
              <%= course.start_time.strftime("%l:%M %p") %> - <%= course.end_time.strftime("%l:%M %p") %>
            </div>



            <!-- <p class="level"><%= course.level %> </p> -->
          </div>
        </div>
      </div>
  </div>

app/views/courses/_course_description_icons.html.erb
<div class="course-description">
  <div class="duration course-icon-description">
    <div class="category-image">
      <%= cl_image_tag 'clock_abwox3' %>
    </div>
    <div class="category-description">
      <%= ((@course.end_time - @course.start_time)/60).round %> mins
    </div>
  </div>
  <div class="course-category course-icon-description">
    <div class="category-image">
      <% case @course.category %>
      <% when "Yoga" %>
        <%= cl_image_tag 'buddhist-yoga-pose_mgof1t' %>
        <% when "Pilates" %>
        <%= cl_image_tag 'buddhist-yoga-pose_mgof1t' %>
      <% when "Crossfit" %>
        <%= cl_image_tag 'weightlifting_xt40om' %>
      <% when "Kickboxing", "Martial Arts" %>
        <%=  cl_image_tag 'mma_ocfpf0' %>
      <% when "Dance" %>
        <%= cl_image_tag 'dancer_yncg7a' %>
      <% when "HIIT" %>
        <%= cl_image_tag 'stretch_ee1nkk' %>
      <% end %>
    </div>
    <div class="category-description">
      <%= @course.category %>
    </div>
  </div>
  <div class="course-intensity course-icon-description">
    <div class="category-image">
      <%= cl_image_tag 'settings_y1kkba' %>
    </div>
    <div class="category-description">
      <%= @course.level %>
    </div>
  </div>
</div>

<div class="class-description-container">
  <div class="class-description">
    <h4 class="classes-heading-small"> About this course </h4>
    <p> <%= @course.description %></p>
    <div id="course-12<%= @course.id %>">
      <%= render "courses/course_favorite_button", course: @course %>
    </div> 
  </div>
</div>

app/views/courses/_course_favorite_button.html.erb
<% if current_user %>
  <% favorite = Favorite.where(course_id: course.id, user_id: current_user.id).first %>
  <% if favorite %>
    <%= form_tag favorite_path(favorite.id), method: :delete, remote: :true do %>
      <%= button_tag(type: 'submit', class: "bookmark-btn") do %>
        <i class="fa fa-heart heart-red"></i>
      <% end %>
    <% end %>
  <% else %>
    <%= form_tag favorites_path(course_id: course.id, user_id: current_user.id), method: :post, remote: true do %>
      <%= button_tag(type: 'submit', class: "bookmark-btn") do %>
        <i class="fa fa-heart-o heart-grey"></i>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/courses/_course_studio.html.erb
<div class="studio-address-map">
  <div class="studio-info">
    <h4 class="classes-heading-small">The Studio</h4>
    <p class="studio-address"><strong> <%= @course.studio.name %> </strong></br> <%= @course.studio.address %></p>
  </div>

  <p class="studio-address"> <%= @json_distance%> away</p>

</div>

app/views/courses/_filter_search.html.erb
<div class="filter-wrapper" style="background: linear-gradient(0deg, rgba(36, 149, 191,0.6) 0%, rgba(30, 62, 119,0.8) 50%);">

  <div class="filter-container">
    <ul class="search-buttons-container nav nav-tab">
      <li><a data-toggle="tab" href="#day-tab"><i class="fa fa-calendar search-tab-button"></i></a></li>
      <li><a data-toggle="tab" href="#category-tab"><i class="fa fa-filter search-tab-button"></i></a></li>
      <li><a data-toggle="tab" href="#level-tab"><i class="fa fa-sliders search-tab-button"></i></a></li>
      <li><a data-toggle="tab" href="#distance-tab"><i class="fa fa-map-marker search-tab-button"></i></a></li>
      <li><a data-toggle="tab" href="#price_cents-tab"><i class="fa fa-eur search-tab-button"></i></a></li>
    </ul>
  </div>

  <!-- Rendering ajax form on search results  - by default, no filter -->
  <%= render 'courses/form_filters'  %>


  <!-- where the active filters appear -->
  <div class="chosen-filters-container">
    <div class="chosen-filters">
      <div class="chosen-category" id="chosen-day">
        <% if params[:search_day] %>
          <p class="chosen-item">x    <%= params[:search_day] %> </p>
        <% end %>
      </div>
      <% @filters.drop(1).each do |f| %>
        <div class="chosen-category" id='chosen-<%= f %>'>
        </div>
      <% end %>
    </div>
    <div class="refresh-button" data-day="Any day" data-level="" data-category="" data-distance="" data-price_cents="">
      <i class="fa fa-refresh" aria-hidden="true"></i>
    </div>
  </div>

  <div class="tab-content hidden">
    <div id="day-tab" class="tab-pane fade in active">
      <div class="days-container">
        <button type="button" class="button-search-options button-day <%= "active" if params[:search_day] == "Today" %>" data-day="Today"><p>Today</p></button>
        <button type="button" class="button-search-options button-day" data-day="Tomorrow"><p>Tomorrow</p></button>
        <button type="button" class="button-search-options button-day" data-day="Any day"><p>+7 Days</p></button>
      </div>
    </div>


    <div id="category-tab" class="tab-pane fade">
      <div class="category-buttons-container">
        <div class="button-category" data-category= "Yoga">
          <%= cl_image_tag 'buddhist-yoga-pose_mgof1t', class: "category-button-image" %>
          <p class="category-text">Yoga</p>
        </div>
        <div class="button-category" data-category= "Crossfit">
          <%= cl_image_tag 'weightlifting_xt40om', class: "category-button-image" %>
          <p class="category-text">Crossfit</p>
        </div>
        <div class="button-category" data-category= "Dance">
          <%= cl_image_tag 'dancer_yncg7a', class: "category-button-image" %>
          <p class="category-text">Dance</p>
        </div>
        <div class="button-category" data-category= "Kickboxing">
          <%= cl_image_tag 'mma_ocfpf0', class: "category-button-image" %>
          <p class="category-text">Kickboxing</p>
        </div>
        <div class="button-category" data-category= "HIIT">
          <%= cl_image_tag 'stretch_ee1nkk', class: "category-button-image" %>
          <p class="category-text">HIIT</p>
        </div>
        <div class="button-category" data-category= "Pilates">
          <%= cl_image_tag 'buddhist-yoga-pose_mgof1t', class: "category-button-image" %>
          <p class="category-text">Pilates</p>
        </div>
        <div class="button-category" data-category= "Martial Arts">
          <%= cl_image_tag 'mma_ocfpf0', class: "category-button-image" %>
          <p class="category-text">Martial Arts</p>
        </div>
      </div>
    </div>

    <div id="level-tab" class="tab-pane fade">
      <div class="level-container">
        <% levels = ["Beginner", "Intermediate", "Advanced"] %>
        <% levels.each do |l| %>
          <button type="button" class="btn button-search-options button-level" data-level= '<%= l %>' ><p><%= l %></p></button>
        <% end %>
      </div>
    </div>

    <div id="distance-tab" class="tab-pane fade">
      <div class="distance-container">
      <p>0 km</p>
        <input type="text" class="slider" id="distance-slider" data-slider-min="0" data-slider-max="10" data-slider-value="10" data-slider-step="1" data-slider-selection="after" data-slider-tooltip="show">
        <p>10 km</p>
      </div>
    </div>

    <div id="price_cents-tab" class="tab-pane fade">
      <div class="price_cents-container">
        <% prices = ["€", "€€", "€€€"] %>
        <% prices.each do |price| %>
          <button type="button" class="btn button-search-options button-price_cents" data-price_cents='<%= price %>' ><p><%= price %></p></button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/courses/_form_filters.html.erb
<div class="form-filters">
  <%= form_for :search_courses, url: "/courses/search_courses", remote: true, method: :post, html: { id: 'search_courses' } do |f| %>
    <%= f.text_field :day, value: params[:search_day], class: "hidden"%>
    <%= f.text_field :category, value: "", class: "hidden" %>
    <%= f.text_field :level, value: "", class: "hidden" %>
    <%= f.text_field :price_cents, value: "", class: "hidden" %>
    <%= f.range_field :distance, :min=>0, :max=>10, :class=>"slide", :id=>"slider-distance-form", class: "hidden" %>
    <% f.submit %>
  <% end %>
</div>

app/views/courses/_form_new_course.html.erb
<%= simple_form_for(@course) do |f| %>
  <div class="container">
    <div class="form-inputs">

      <%= f.input :title, required: true, autofocus: true %>
      <%= f.input :start_time, required: true, autofocus: true %>
      <%= f.input :end_time, required: true, autofocus: true %>
      <%= f.input :spots, required: true, autofocus: true %>
      <%= f.input :description, required: true, autofocus: true %>
      <%= f.input :category, required: true, autofocus: true %>
      <%= f.input :level, required: true, autofocus: true %>
      <%= f.submit "Register course", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/courses/_instructor.html.erb
<div class="course-instructor">
  <h4 class="classes-heading-small">
    Meet your instructor
  </h4>
  <div class="instructor-content">
    <div class="instructor-name">

      <%= @course.instructor.first_name %> (<%= @course.instructor.age %>)
      <p class="find-out">Find out more about <%= @course.instructor.first_name %></p>
      <div class="instructor-description hidden">
        <%= @course.instructor.description %>
        <ul>
          <% @course.instructor.areas.each do |area| %>
          <li><%= area.name %></li>
          <% end %>
        </ul>
      </div>
      <p class="find-out hidden">Show less</p>
    </div>
    <%= cl_image_tag @course.instructor.cld_id, class: "profile-picture-medium " %>
  </div>
</div>


<%content_for(:after_js) do %>
<script>

  $(function(){
    $('.find-out').click(function(event){
      $(this).siblings('.instructor-description').toggleClass('hidden');
      $(this).toggleClass('hidden');
      $(this).siblings('p').toggleClass('hidden');
        // $(this).siblings('item-long').removeClass('hidden');
        // $(this).siblings('hide-item').removeClass('hidden');
      });
  });


</script>
<% end %>

app/views/courses/_map.html.erb
<div class="call_to_action">
<%= link_to 'Check out the Studio', studio_path(@studio.id), class: "call-to-action-button studio-address border-right-cta" %>

<%= link_to 'Get directions', "https://maps.google.com?saddr=#{@la.to_s},#{@lo.to_s}&daddr=#{URI.encode(@course.studio.address)}&mode=bicycling&key=#{ENV['GOOGLE_API_SERVER_KEY']}", class: "call-to-action-button studio-address" %>
</div>
<div id="map" style="width: 100%; height: 150px;">

  <% content_for(:after_js) do %>
    <%= javascript_tag do %>
        $(document).ready(function() {
            var handler = Gmaps.build('Google');
            handler.buildMap({ internal: { id: 'map' } }, function() {
            markers = handler.addMarkers(<%= raw @hash.to_json %>);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            if (markers.length == 0) {
            <!-- handler.getMap().setZoom(2); -->
            } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
            }
        });
    });
    <% end %>
  <% end %>
</div>

app/views/courses/_map_box.html.erb
<p><i class="fa fa-car"></i><%= @json_driving %></p>
<p><i class="fa fa-subway"></i><%= @json_transit %></p>
<p><%= cl_image_tag 'pedestrian-walking_zuyyvo', class: 'walker' %><%= @json_walking %></p>
<p><i class="fa fa-bicycle"></i><%= @json_bicycle %></p>

app/views/courses/_show_top_content.html.erb
<!-- This File is for Reveiws#new to render the top section of courses#show view -->

<!-- Course Title banner -->


<% if @course.studio.photo %>
  <div class="course-banner" style="background-image: linear-gradient(to right bottom, rgba(10,10,10,0.6), rgba(100,100,100,0.6)),url('<%= cl_image_path @course.studio.photo.path %>');">
<% else %>
  <div class="course-banner" style="background-image: linear-gradient(to right bottom, rgba(10,10,10,0.6), rgba(100,100,100,0.6)),url('<%= cl_image_path @course.studio.cld_id %>');">
<% end %>

  <div class="course-banner-content">
    <h3 class="course-show-title text-center"><%= course.title %></h3>
    <div class="star-ratings-css-medium text-center">
      <%= render 'shared/stars', course: course %>
    </div>
  </div>
</div>

<!-- Time & Cost -->
<div class="blue-banner" style="background: $light-gray; height: 5vh;">
  <%= @date_words %> - <%= @course.start_time.strftime ("%l:%M %P") %>
  <div class="prices">
    <%= humanized_money_with_symbol(@course.price) %>
  </div>
</div>

<%= render 'courses/course_description_icons' %>

app/views/courses/new.html.erb
<div class="container">
<h1>Enter a course here</h1>

<%= render 'form_new_course' %>
</div>

app/views/courses/show.html.erb
<!-- This partial is also rendered in Reviews#new view -->
<%= render 'courses/show_top_content', course: @course %>

<%= render 'reviews/index' %>

<div class="room-for-button">
  <%= render 'courses/course_studio' %>
  <%= render 'courses/map' %>
</div>

<% if @existing_booking %>
  <%= link_to user_path(current_user) do %>
    <button class="new-booking-button text-center">
      <h3 class="new-booking-heading">View Your Booking</h3>
    </button>
  <% end %>
<% else %>
  <div class="payment">
    <%= simple_form_for @booking, remote: true do |f| %>
      <%= f.input :course_id, input_html: {value:  @course.id}, as: :hidden %>
      <%= f.button :submit, "Join", class: 'new-booking-button new-booking-button-join' %>
    <% end %>
  </div>
<% end %>

<div id="payment-modal">
  <% if @booking.persisted? %>
    <%= render 'payments/new', booking: @booking %>
  <% end %>
</div>

<% if current_user %>
  <%= render 'bookings/new', course: @course, date_words: @date_words %>
<% else %>
  <%= render 'bookings/login', course: @course, date_words: @date_words %>
<% end %>

app/views/courses/update_index.js.erb
$("#render_courses").html(
  "<%= j render 'course_list', courses: @update_courses %>"

);